<?php

namespace Levi\Agent\AI\Tools;

use Levi\Agent\AI\Tools\Concerns\ValidatesSyntax;

class CreateThemeTool extends AbstractTool {

    use ValidatesSyntax;

    public function getName(): string {
        return 'create_theme';
    }

    public function getDescription(): string {
        return 'Create a new WordPress child or standalone theme scaffold with style.css, functions.php, and index.php. '
            . 'The theme slug must be unique — refuses creation if a theme with the same slug already exists. '
            . 'Optionally activates the theme immediately after creation. '
            . 'Use write_theme_file to add additional template files afterwards.';
    }

    public function getParameters(): array {
        return [
            'slug' => [
                'type' => 'string',
                'description' => 'Theme slug, e.g. "my-custom-theme"',
                'required' => true,
            ],
            'name' => [
                'type' => 'string',
                'description' => 'Theme display name',
                'required' => true,
            ],
            'description' => [
                'type' => 'string',
                'description' => 'Short theme description',
            ],
            'author' => [
                'type' => 'string',
                'description' => 'Theme author',
            ],
            'version' => [
                'type' => 'string',
                'description' => 'Initial version',
                'default' => '1.0.0',
            ],
            'activate' => [
                'type' => 'boolean',
                'description' => 'Activate theme after creating files',
                'default' => false,
            ],
            'overwrite' => [
                'type' => 'boolean',
                'description' => 'Overwrite existing style.css if it exists',
                'default' => false,
            ],
        ];
    }

    public function checkPermission(): bool {
        return current_user_can('edit_themes') || current_user_can('switch_themes');
    }

    public function execute(array $params): array {
        $slug = sanitize_title($params['slug'] ?? '');
        $name = sanitize_text_field($params['name'] ?? '');
        $description = sanitize_text_field($params['description'] ?? 'Generated by Levi Agent');
        $author = sanitize_text_field($params['author'] ?? wp_get_current_user()->display_name);
        $version = sanitize_text_field($params['version'] ?? '1.0.0');
        $activate = (bool) ($params['activate'] ?? false);
        $overwrite = (bool) ($params['overwrite'] ?? false);

        if ($slug === '' || $name === '') {
            return ['success' => false, 'error' => 'Both slug and name are required.'];
        }

        $themeDir = trailingslashit(get_theme_root()) . $slug;
        $styleCss = $themeDir . '/style.css';

        $filesystem = $this->getFilesystem();
        if ($filesystem === null) {
            return ['success' => false, 'error' => 'WordPress filesystem is not available.'];
        }

        $hadStyleCss = $filesystem->exists($styleCss);
        $previousStyleContent = null;
        if ($hadStyleCss) {
            $previousStyleContent = $filesystem->get_contents($styleCss);
            if (!is_string($previousStyleContent)) {
                return ['success' => false, 'error' => 'Could not read existing style.css for safety backup.'];
            }
        }

        if (!$filesystem->is_dir($themeDir) && !$filesystem->mkdir($themeDir, FS_CHMOD_DIR, true)) {
            return ['success' => false, 'error' => 'Could not create theme directory.'];
        }

        if ($filesystem->exists($styleCss) && !$overwrite) {
            return [
                'success' => false,
                'error' => 'style.css already exists. Set overwrite=true to replace it.',
                'theme_slug' => $slug,
            ];
        }

        $styleContent = "/*\n"
            . "Theme Name: {$name}\n"
            . "Theme URI: \n"
            . "Description: {$description}\n"
            . "Author: {$author}\n"
            . "Version: {$version}\n"
            . "Text Domain: {$slug}\n"
            . "*/\n\n"
            . "/* Theme styles */\n";

        if (!$filesystem->put_contents($styleCss, $styleContent, FS_CHMOD_FILE)) {
            return ['success' => false, 'error' => 'Could not write style.css.'];
        }

        $functionsContent = "<?php\n"
            . "/**\n"
            . " * Theme functions and definitions.\n"
            . " *\n"
            . " * @package {$name}\n"
            . " */\n\n"
            . "if (!defined('ABSPATH')) {\n"
            . "    exit;\n"
            . "}\n\n"
            . "add_action('after_setup_theme', function () {\n"
            . "    add_theme_support('title-tag');\n"
            . "    add_theme_support('post-thumbnails');\n"
            . "});\n";

        $functionsPath = $themeDir . '/functions.php';
        if (!$filesystem->put_contents($functionsPath, $functionsContent, FS_CHMOD_FILE)) {
            return ['success' => false, 'error' => 'Could not write functions.php.'];
        }

        $lint = $this->validatePhpSyntax($functionsPath);
        if (($lint['valid'] ?? false) !== true) {
            $filesystem->delete($functionsPath, false, 'f');
            if ($hadStyleCss && is_string($previousStyleContent)) {
                $filesystem->put_contents($styleCss, $previousStyleContent, FS_CHMOD_FILE);
            } else {
                $filesystem->delete($styleCss, false, 'f');
            }
            return [
                'success' => false,
                'error' => 'Create reverted: PHP syntax error in functions.php. ' . ($lint['error'] ?? ''),
            ];
        }

        $indexContent = "<?php\n"
            . "/**\n"
            . " * Main template file.\n"
            . " *\n"
            . " * @package {$name}\n"
            . " */\n\n"
            . "get_header();\n"
            . "?>\n"
            . "<main class=\"site-main\">\n"
            . "<?php\n"
            . "if (have_posts()) {\n"
            . "    while (have_posts()) {\n"
            . "        the_post();\n"
            . "        the_content();\n"
            . "    }\n"
            . "}\n"
            . "?>\n"
            . "</main>\n"
            . "<?php get_footer(); ?>\n";

        $indexPath = $themeDir . '/index.php';
        if (!$filesystem->put_contents($indexPath, $indexContent, FS_CHMOD_FILE)) {
            return ['success' => false, 'error' => 'Could not write index.php.'];
        }

        $lintIndex = $this->validatePhpSyntax($indexPath);
        if (($lintIndex['valid'] ?? false) !== true) {
            $filesystem->delete($indexPath, false, 'f');
            $filesystem->delete($functionsPath, false, 'f');
            if ($hadStyleCss && is_string($previousStyleContent)) {
                $filesystem->put_contents($styleCss, $previousStyleContent, FS_CHMOD_FILE);
            } else {
                $filesystem->delete($styleCss, false, 'f');
            }
            return [
                'success' => false,
                'error' => 'Create reverted: PHP syntax error in index.php. ' . ($lintIndex['error'] ?? ''),
            ];
        }

        $activated = false;
        if ($activate) {
            $themeObj = wp_get_theme($slug);
            if (!$themeObj->exists()) {
                return [
                    'success' => false,
                    'error' => 'Theme created but could not be activated (theme not found).',
                    'theme_slug' => $slug,
                ];
            }
            switch_theme($slug);
            $activated = true;
        }

        $result = [
            'success' => true,
            'slug' => $slug,
            'theme_slug' => $slug,
            'path' => $themeDir,
            'created_files' => ['style.css', 'functions.php', 'index.php'],
            'activated' => $activated,
            'message' => $activated
                ? 'Theme scaffold created and activated.'
                : 'Theme scaffold created.',
        ];

        if (!empty($lint['warning'])) {
            $result['warning'] = $lint['warning'];
        }

        return $result;
    }
}
