<?php

namespace Levi\Agent\AI\Tools;

class CreateThemeTool implements ToolInterface {

    public function getName(): string {
        return 'create_theme';
    }

    public function getDescription(): string {
        return 'Create a new WordPress theme scaffold (directory + style.css + functions.php + index.php), optionally activate it.';
    }

    public function getParameters(): array {
        return [
            'slug' => [
                'type' => 'string',
                'description' => 'Theme slug, e.g. "my-custom-theme"',
                'required' => true,
            ],
            'name' => [
                'type' => 'string',
                'description' => 'Theme display name',
                'required' => true,
            ],
            'description' => [
                'type' => 'string',
                'description' => 'Short theme description',
            ],
            'author' => [
                'type' => 'string',
                'description' => 'Theme author',
            ],
            'version' => [
                'type' => 'string',
                'description' => 'Initial version',
                'default' => '1.0.0',
            ],
            'activate' => [
                'type' => 'boolean',
                'description' => 'Activate theme after creating files',
                'default' => false,
            ],
            'overwrite' => [
                'type' => 'boolean',
                'description' => 'Overwrite existing style.css if it exists',
                'default' => false,
            ],
        ];
    }

    public function checkPermission(): bool {
        return current_user_can('edit_themes') || current_user_can('switch_themes');
    }

    public function execute(array $params): array {
        $slug = sanitize_title($params['slug'] ?? '');
        $name = sanitize_text_field($params['name'] ?? '');
        $description = sanitize_text_field($params['description'] ?? 'Generated by Levi Agent');
        $author = sanitize_text_field($params['author'] ?? wp_get_current_user()->display_name);
        $version = sanitize_text_field($params['version'] ?? '1.0.0');
        $activate = (bool) ($params['activate'] ?? false);
        $overwrite = (bool) ($params['overwrite'] ?? false);

        if ($slug === '' || $name === '') {
            return [
                'success' => false,
                'error' => 'Both slug and name are required.',
            ];
        }

        $themeDir = trailingslashit(get_theme_root()) . $slug;
        $styleCss = $themeDir . '/style.css';
        $filesystem = $this->getFilesystem();
        if ($filesystem === null) {
            return [
                'success' => false,
                'error' => 'WordPress filesystem is not available.',
            ];
        }
        $hadStyleCss = $filesystem->exists($styleCss);
        $previousStyleContent = null;
        if ($hadStyleCss) {
            $previousStyleContent = $filesystem->get_contents($styleCss);
            if (!is_string($previousStyleContent)) {
                return [
                    'success' => false,
                    'error' => 'Could not read existing style.css for safety backup.',
                ];
            }
        }

        if (!$filesystem->is_dir($themeDir) && !$filesystem->mkdir($themeDir, FS_CHMOD_DIR, true)) {
            return [
                'success' => false,
                'error' => 'Could not create theme directory.',
            ];
        }

        if ($filesystem->exists($styleCss) && !$overwrite) {
            return [
                'success' => false,
                'error' => 'style.css already exists. Set overwrite=true to replace it.',
                'theme_slug' => $slug,
            ];
        }

        $styleContent = "/*\n"
            . "Theme Name: {$name}\n"
            . "Theme URI: \n"
            . "Description: {$description}\n"
            . "Author: {$author}\n"
            . "Version: {$version}\n"
            . "Text Domain: {$slug}\n"
            . "*/\n\n"
            . "/* Theme styles */\n";

        if (!$filesystem->put_contents($styleCss, $styleContent, FS_CHMOD_FILE)) {
            return [
                'success' => false,
                'error' => 'Could not write style.css via WordPress filesystem.',
            ];
        }

        $functionsContent = "<?php\n"
            . "/**\n"
            . " * Theme functions and definitions.\n"
            . " *\n"
            . " * @package {$name}\n"
            . " */\n\n"
            . "if (!defined('ABSPATH')) {\n"
            . "    exit;\n"
            . "}\n\n"
            . "add_action('after_setup_theme', function () {\n"
            . "    add_theme_support('title-tag');\n"
            . "    add_theme_support('post-thumbnails');\n"
            . "});\n";

        $functionsPath = $themeDir . '/functions.php';
        if (!$filesystem->put_contents($functionsPath, $functionsContent, FS_CHMOD_FILE)) {
            return [
                'success' => false,
                'error' => 'Could not write functions.php via WordPress filesystem.',
            ];
        }
        $lint = $this->validatePhpSyntax($functionsPath);
        if (($lint['valid'] ?? false) !== true) {
            $filesystem->delete($functionsPath, false, 'f');
            if ($hadStyleCss && is_string($previousStyleContent)) {
                $filesystem->put_contents($styleCss, $previousStyleContent, FS_CHMOD_FILE);
            } else {
                $filesystem->delete($styleCss, false, 'f');
            }
            return [
                'success' => false,
                'error' => 'Create reverted: PHP syntax check failed for functions.php. ' . ($lint['error'] ?? 'Unknown lint error.'),
            ];
        }

        $indexContent = "<?php\n"
            . "/**\n"
            . " * Main template file.\n"
            . " *\n"
            . " * @package {$name}\n"
            . " */\n\n"
            . "get_header();\n"
            . "?>\n"
            . "<main class=\"site-main\">\n"
            . "<?php\n"
            . "if (have_posts()) {\n"
            . "    while (have_posts()) {\n"
            . "        the_post();\n"
            . "        the_content();\n"
            . "    }\n"
            . "}\n"
            . "?>\n"
            . "</main>\n"
            . "<?php get_footer(); ?>\n";

        $indexPath = $themeDir . '/index.php';
        if (!$filesystem->put_contents($indexPath, $indexContent, FS_CHMOD_FILE)) {
            return [
                'success' => false,
                'error' => 'Could not write index.php via WordPress filesystem.',
            ];
        }
        $lintIndex = $this->validatePhpSyntax($indexPath);
        if (($lintIndex['valid'] ?? false) !== true) {
            $filesystem->delete($indexPath, false, 'f');
            $filesystem->delete($functionsPath, false, 'f');
            if ($hadStyleCss && is_string($previousStyleContent)) {
                $filesystem->put_contents($styleCss, $previousStyleContent, FS_CHMOD_FILE);
            } else {
                $filesystem->delete($styleCss, false, 'f');
            }
            return [
                'success' => false,
                'error' => 'Create reverted: PHP syntax check failed for index.php. ' . ($lintIndex['error'] ?? 'Unknown lint error.'),
            ];
        }

        $activated = false;
        if ($activate) {
            $themeObj = wp_get_theme($slug);
            if (!$themeObj->exists()) {
                return [
                    'success' => false,
                    'error' => 'Theme was created but could not be activated (theme not found).',
                    'theme_slug' => $slug,
                ];
            }
            switch_theme($slug);
            $activated = true;
        }

        $result = [
            'success' => true,
            'slug' => $slug,
            'theme_slug' => $slug,
            'path' => $themeDir,
            'activated' => $activated,
            'message' => $activated
                ? 'Theme scaffold created and activated.'
                : 'Theme scaffold created.',
        ];
        if (!empty($lint['warning'])) {
            $result['warning'] = $lint['warning'];
        }
        return $result;
    }

    private function validatePhpSyntax(string $path): array {
        if (strtolower((string) pathinfo($path, PATHINFO_EXTENSION)) !== 'php') {
            return ['valid' => true];
        }

        if (!function_exists('exec')) {
            return [
                'valid' => true,
                'warning' => 'PHP lint skipped (exec unavailable).',
            ];
        }

        $output = [];
        $exitCode = 0;
        @exec('php -l ' . escapeshellarg($path) . ' 2>&1', $output, $exitCode);
        if ($exitCode !== 0) {
            return [
                'valid' => false,
                'error' => trim(implode("\n", $output)) ?: 'PHP lint failed.',
            ];
        }

        return ['valid' => true];
    }

    private function getFilesystem(): ?\WP_Filesystem_Base {
        if (!function_exists('WP_Filesystem')) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if (!WP_Filesystem()) {
            return null;
        }

        global $wp_filesystem;
        if (!($wp_filesystem instanceof \WP_Filesystem_Base)) {
            return null;
        }

        return $wp_filesystem;
    }
}
