<?php

namespace Levi\Agent\AI\Tools;

class CreatePluginTool implements ToolInterface {

    public function getName(): string {
        return 'create_plugin';
    }

    public function getDescription(): string {
        return 'Create a NEW WordPress plugin scaffold (directory + main plugin file), optionally activate it. '
            . 'This tool ONLY creates new plugins — it will refuse if a plugin with the same slug already exists. '
            . 'To modify an existing plugin, use write_plugin_file instead. '
            . 'Always choose a unique slug that does not collide with existing plugins.';
    }

    public function getParameters(): array {
        return [
            'slug' => [
                'type' => 'string',
                'description' => 'Plugin slug, e.g. "my-custom-plugin"',
                'required' => true,
            ],
            'name' => [
                'type' => 'string',
                'description' => 'Plugin display name',
                'required' => true,
            ],
            'description' => [
                'type' => 'string',
                'description' => 'Short plugin description',
            ],
            'author' => [
                'type' => 'string',
                'description' => 'Plugin author',
            ],
            'version' => [
                'type' => 'string',
                'description' => 'Initial version',
                'default' => '0.1.0',
            ],
            'activate' => [
                'type' => 'boolean',
                'description' => 'Activate plugin after creating files',
                'default' => false,
            ],
            'allow_wporg_slug_collision' => [
                'type' => 'boolean',
                'description' => 'Allow using a slug that already exists on wordpress.org',
                'default' => false,
            ],
        ];
    }

    public function checkPermission(): bool {
        return current_user_can('install_plugins') || current_user_can('activate_plugins');
    }

    public function execute(array $params): array {
        $slug = sanitize_title($params['slug'] ?? '');
        $name = sanitize_text_field($params['name'] ?? '');
        $description = sanitize_text_field($params['description'] ?? 'Generated by Levi Agent');
        $author = sanitize_text_field($params['author'] ?? wp_get_current_user()->display_name);
        $version = sanitize_text_field($params['version'] ?? '0.1.0');
        $activate = (bool) ($params['activate'] ?? false);
        $allowWpOrgSlugCollision = (bool) ($params['allow_wporg_slug_collision'] ?? false);

        if ($slug === '' || $name === '') {
            return [
                'success' => false,
                'error' => 'Both slug and name are required.',
            ];
        }

        if (!$allowWpOrgSlugCollision) {
            if (!function_exists('plugins_api')) {
                require_once ABSPATH . 'wp-admin/includes/plugin-install.php';
            }
            $api = plugins_api('plugin_information', [
                'slug' => $slug,
                'fields' => ['sections' => false],
            ]);
            if (!is_wp_error($api) && is_object($api) && !empty($api->name)) {
                return [
                    'success' => false,
                    'error' => 'Slug already exists on wordpress.org. Choose a unique slug (e.g. your-brand-' . $slug . ') or set allow_wporg_slug_collision=true.',
                    'conflicting_slug' => $slug,
                ];
            }
        }

        $pluginDir = trailingslashit(WP_PLUGIN_DIR) . $slug;
        $mainFile = $pluginDir . '/' . $slug . '.php';
        $pluginBasename = $slug . '/' . $slug . '.php';
        $filesystem = $this->getFilesystem();
        if ($filesystem === null) {
            return [
                'success' => false,
                'error' => 'WordPress filesystem is not available.',
            ];
        }

        if ($filesystem->exists($mainFile)) {
            return [
                'success' => false,
                'error' => "A plugin with slug '$slug' already exists. Choose a different, unique slug for the new plugin. "
                    . "If you want to modify the existing plugin, use write_plugin_file instead.",
                'existing_plugin' => $pluginBasename,
            ];
        }

        if (!$filesystem->is_dir($pluginDir) && !$filesystem->mkdir($pluginDir, FS_CHMOD_DIR, true)) {
            return [
                'success' => false,
                'error' => 'Could not create plugin directory.',
            ];
        }

        $pluginContent = "<?php\n"
            . "/**\n"
            . " * Plugin Name: {$name}\n"
            . " * Description: {$description}\n"
            . " * Version: {$version}\n"
            . " * Author: {$author}\n"
            . " * Text Domain: {$slug}\n"
            . " * Update URI: false\n"
            . " */\n\n"
            . "if (!defined('ABSPATH')) {\n"
            . "    exit;\n"
            . "}\n\n"
            . "add_action('init', function () {\n"
            . "    // Plugin bootstrapped by Levi Agent.\n"
            . "});\n";

        if (!$filesystem->put_contents($mainFile, $pluginContent, FS_CHMOD_FILE)) {
            return [
                'success' => false,
                'error' => 'Could not write main plugin file via WordPress filesystem.',
            ];
        }
        $lint = $this->validatePhpSyntax($mainFile);
        if (($lint['valid'] ?? false) !== true) {
            $filesystem->delete($mainFile, false, 'f');
            return [
                'success' => false,
                'error' => 'Create reverted: PHP syntax check failed for main plugin file. ' . ($lint['error'] ?? 'Unknown lint error.'),
            ];
        }

        $readme = "# {$name}\n\n{$description}\n";
        $filesystem->put_contents($pluginDir . '/README.md', $readme, FS_CHMOD_FILE);

        $activated = false;
        if ($activate) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
            $activationResult = activate_plugin($pluginBasename);
            if (is_wp_error($activationResult)) {
                return [
                    'success' => false,
                    'error' => $activationResult->get_error_message(),
                    'plugin_file' => $pluginBasename,
                ];
            }
            $activated = true;
        }

        $result = [
            'success' => true,
            'slug' => $slug,
            'plugin_file' => $pluginBasename,
            'path' => $mainFile,
            'activated' => $activated,
            'created_new' => true,
            'message' => $activated
                ? 'New plugin scaffold created and activated.'
                : 'New plugin scaffold created (not activated).',
        ];
        if (!empty($lint['warning'])) {
            $result['warning'] = $lint['warning'];
        }
        return $result;
    }

    private function validatePhpSyntax(string $path): array {
        if (strtolower((string) pathinfo($path, PATHINFO_EXTENSION)) !== 'php') {
            return ['valid' => true];
        }

        if (!function_exists('exec')) {
            return [
                'valid' => true,
                'warning' => 'PHP lint skipped (exec unavailable).',
            ];
        }

        $output = [];
        $exitCode = 0;
        @exec('php -l ' . escapeshellarg($path) . ' 2>&1', $output, $exitCode);
        if ($exitCode !== 0) {
            return [
                'valid' => false,
                'error' => trim(implode("\n", $output)) ?: 'PHP lint failed.',
            ];
        }

        return ['valid' => true];
    }

    private function getFilesystem(): ?\WP_Filesystem_Base {
        if (!function_exists('WP_Filesystem')) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        if (!WP_Filesystem()) {
            return null;
        }

        global $wp_filesystem;
        if (!($wp_filesystem instanceof \WP_Filesystem_Base)) {
            return null;
        }

        return $wp_filesystem;
    }
}
