<?php

namespace Levi\Agent\AI\Tools;

use Levi\Agent\AI\Tools\Concerns\ValidatesSyntax;

class CreatePluginTool extends AbstractTool {

    use ValidatesSyntax;

    private const VALID_TYPES = ['plain', 'woocommerce', 'elementor'];
    private const VALID_FEATURES = ['admin-settings', 'frontend-css', 'frontend-js', 'rest-api'];

    public function getName(): string {
        return 'create_plugin';
    }

    public function getDescription(): string {
        return 'Create a new WordPress plugin scaffold with correct header, directory structure, and boilerplate. '
            . 'Use plugin_type to generate WooCommerce or Elementor-specific scaffolds. '
            . 'Use features to auto-generate admin settings, frontend assets, or REST API endpoints. '
            . 'Refuses if a plugin with the same slug already exists.';
    }

    public function getInputExamples(): array {
        return [
            ['slug' => 'my-simple-plugin', 'name' => 'My Simple Plugin', 'description' => 'A simple utility plugin'],
            ['slug' => 'wc-custom-shipping', 'name' => 'WC Custom Shipping', 'plugin_type' => 'woocommerce', 'features' => ['admin-settings']],
            ['slug' => 'elementor-fancy-widgets', 'name' => 'Fancy Widgets', 'plugin_type' => 'elementor', 'features' => ['frontend-css', 'frontend-js']],
        ];
    }

    public function getParameters(): array {
        return [
            'slug' => [
                'type' => 'string',
                'description' => 'Plugin slug, e.g. "my-custom-plugin"',
                'required' => true,
            ],
            'name' => [
                'type' => 'string',
                'description' => 'Plugin display name',
                'required' => true,
            ],
            'description' => [
                'type' => 'string',
                'description' => 'Short plugin description',
            ],
            'author' => [
                'type' => 'string',
                'description' => 'Plugin author',
            ],
            'version' => [
                'type' => 'string',
                'description' => 'Initial version',
                'default' => '0.1.0',
            ],
            'plugin_type' => [
                'type' => 'string',
                'description' => 'Plugin type: plain (default), woocommerce (adds WC dependency check + settings section), elementor (adds Elementor compatibility check)',
                'enum' => self::VALID_TYPES,
            ],
            'features' => [
                'type' => 'array',
                'description' => 'Optional features to scaffold: admin-settings, frontend-css, frontend-js, rest-api',
                'items' => ['type' => 'string'],
            ],
            'depends_on' => [
                'type' => 'array',
                'description' => 'Additional plugin dependencies (added to Requires Plugins header)',
                'items' => ['type' => 'string'],
            ],
            'activate' => [
                'type' => 'boolean',
                'description' => 'Activate plugin after creating files',
                'default' => false,
            ],
            'allow_wporg_slug_collision' => [
                'type' => 'boolean',
                'description' => 'Allow using a slug that already exists on wordpress.org',
                'default' => false,
            ],
        ];
    }

    public function checkPermission(): bool {
        return current_user_can('install_plugins') || current_user_can('activate_plugins');
    }

    public function execute(array $params): array {
        $slug = sanitize_title($params['slug'] ?? '');
        $name = sanitize_text_field($params['name'] ?? '');
        $description = sanitize_text_field($params['description'] ?? 'Generated by Levi Agent');
        $author = sanitize_text_field($params['author'] ?? wp_get_current_user()->display_name);
        $version = sanitize_text_field($params['version'] ?? '0.1.0');
        $pluginType = (string) ($params['plugin_type'] ?? 'plain');
        $features = (array) ($params['features'] ?? []);
        $dependsOn = (array) ($params['depends_on'] ?? []);
        $activate = (bool) ($params['activate'] ?? false);
        $allowWpOrgSlugCollision = (bool) ($params['allow_wporg_slug_collision'] ?? false);

        if ($slug === '' || $name === '') {
            return ['success' => false, 'error' => 'Both slug and name are required.'];
        }

        if (!in_array($pluginType, self::VALID_TYPES, true)) {
            $pluginType = 'plain';
        }

        $features = array_intersect($features, self::VALID_FEATURES);

        if ($pluginType === 'woocommerce' && !in_array('woocommerce', $dependsOn, true)) {
            $dependsOn[] = 'woocommerce';
        }
        if ($pluginType === 'elementor' && !in_array('elementor', $dependsOn, true)) {
            $dependsOn[] = 'elementor';
        }

        if (!$allowWpOrgSlugCollision) {
            $collision = $this->checkWpOrgSlugCollision($slug);
            if ($collision !== null) {
                return $collision;
            }
        }

        $pluginDir = trailingslashit(WP_PLUGIN_DIR) . $slug;
        $mainFile = $pluginDir . '/' . $slug . '.php';
        $pluginBasename = $slug . '/' . $slug . '.php';

        $filesystem = $this->getFilesystem();
        if ($filesystem === null) {
            return ['success' => false, 'error' => 'WordPress filesystem is not available.'];
        }

        if ($filesystem->exists($mainFile)) {
            return [
                'success' => false,
                'error' => "A plugin with slug '$slug' already exists. Choose a different slug. "
                    . "To modify the existing plugin, use write_plugin_file or patch_plugin_file.",
                'existing_plugin' => $pluginBasename,
            ];
        }

        // --- Build directory structure ---
        $dirs = [$pluginDir];
        if (in_array('frontend-css', $features) || in_array('frontend-js', $features)) {
            $dirs[] = $pluginDir . '/assets';
            if (in_array('frontend-css', $features)) {
                $dirs[] = $pluginDir . '/assets/css';
            }
            if (in_array('frontend-js', $features)) {
                $dirs[] = $pluginDir . '/assets/js';
            }
        }
        if (in_array('admin-settings', $features) || in_array('rest-api', $features)) {
            $dirs[] = $pluginDir . '/includes';
        }

        foreach ($dirs as $dir) {
            if (!$filesystem->is_dir($dir) && !$filesystem->mkdir($dir, FS_CHMOD_DIR, true)) {
                return ['success' => false, 'error' => "Could not create directory: $dir"];
            }
        }

        // --- Generate files ---
        $createdFiles = [];

        $header = $this->buildHeader($slug, $name, $description, $author, $version, $dependsOn);
        $body = $this->buildMainFileBody($slug, $name, $version, $pluginType, $features);
        $mainContent = $header . $body;

        if (!$filesystem->put_contents($mainFile, $mainContent, FS_CHMOD_FILE)) {
            return ['success' => false, 'error' => 'Could not write main plugin file.'];
        }
        $createdFiles[] = $slug . '.php';

        $lint = $this->validatePhpSyntax($mainFile);
        if (($lint['valid'] ?? false) !== true) {
            $this->cleanupDir($filesystem, $pluginDir);
            return [
                'success' => false,
                'error' => 'Create reverted: PHP syntax error in main file. ' . ($lint['error'] ?? ''),
                'suggestion' => 'This is likely a scaffold generation bug. Try creating with fewer features or report the issue.',
            ];
        }

        if (in_array('frontend-css', $features)) {
            $cssContent = "/* {$name} – Frontend Styles */\n";
            $cssPath = $pluginDir . '/assets/css/' . $slug . '.css';
            $filesystem->put_contents($cssPath, $cssContent, FS_CHMOD_FILE);
            $createdFiles[] = 'assets/css/' . $slug . '.css';
        }

        if (in_array('frontend-js', $features)) {
            $jsContent = $this->buildFrontendJs($slug);
            $jsPath = $pluginDir . '/assets/js/' . $slug . '.js';
            $filesystem->put_contents($jsPath, $jsContent, FS_CHMOD_FILE);
            $createdFiles[] = 'assets/js/' . $slug . '.js';
        }

        if (in_array('admin-settings', $features)) {
            $settingsContent = $this->buildSettingsFile($slug, $name, $pluginType);
            $settingsPath = $pluginDir . '/includes/class-settings.php';
            $filesystem->put_contents($settingsPath, $settingsContent, FS_CHMOD_FILE);
            $createdFiles[] = 'includes/class-settings.php';

            $settingsLint = $this->validatePhpSyntax($settingsPath);
            if (($settingsLint['valid'] ?? false) !== true) {
                $this->cleanupDir($filesystem, $pluginDir);
                return [
                    'success' => false,
                    'error' => 'Create reverted: PHP syntax error in settings file. ' . ($settingsLint['error'] ?? ''),
                ];
            }
        }

        if (in_array('rest-api', $features)) {
            $restContent = $this->buildRestApiFile($slug, $name);
            $restPath = $pluginDir . '/includes/class-rest-api.php';
            $filesystem->put_contents($restPath, $restContent, FS_CHMOD_FILE);
            $createdFiles[] = 'includes/class-rest-api.php';

            $restLint = $this->validatePhpSyntax($restPath);
            if (($restLint['valid'] ?? false) !== true) {
                $this->cleanupDir($filesystem, $pluginDir);
                return [
                    'success' => false,
                    'error' => 'Create reverted: PHP syntax error in REST API file. ' . ($restLint['error'] ?? ''),
                ];
            }
        }

        $readme = "# {$name}\n\n{$description}\n";
        $filesystem->put_contents($pluginDir . '/README.md', $readme, FS_CHMOD_FILE);
        $createdFiles[] = 'README.md';

        wp_cache_delete('plugins', 'plugins');

        $activated = false;
        if ($activate) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
            $activationResult = activate_plugin($pluginBasename);
            if (is_wp_error($activationResult)) {
                return [
                    'success' => false,
                    'error' => 'Plugin created but activation failed: ' . $activationResult->get_error_message(),
                    'plugin_file' => $pluginBasename,
                    'created_files' => $createdFiles,
                ];
            }
            $activated = true;
        }

        $result = [
            'success' => true,
            'slug' => $slug,
            'plugin_file' => $pluginBasename,
            'path' => $mainFile,
            'plugin_type' => $pluginType,
            'features' => $features,
            'created_files' => $createdFiles,
            'activated' => $activated,
            'message' => $activated
                ? "Plugin scaffold created and activated ({$pluginType}, features: " . implode(', ', $features ?: ['none']) . ').'
                : "Plugin scaffold created ({$pluginType}, features: " . implode(', ', $features ?: ['none']) . ').',
        ];

        if (!empty($lint['warning'])) {
            $result['warning'] = $lint['warning'];
        }

        return $result;
    }

    // ── Header builder ───────────────────────────────────────────────────

    private function buildHeader(
        string $slug,
        string $name,
        string $description,
        string $author,
        string $version,
        array $dependsOn
    ): string {
        $lines = [
            "<?php",
            "/**",
            " * Plugin Name: {$name}",
            " * Description: {$description}",
            " * Version: {$version}",
            " * Author: {$author}",
            " * Text Domain: {$slug}",
            " * Update URI: false",
        ];

        if (!empty($dependsOn)) {
            $lines[] = " * Requires Plugins: " . implode(', ', array_unique($dependsOn));
        }

        $lines[] = " */";
        $lines[] = "";

        return implode("\n", $lines) . "\n";
    }

    // ── Main file body builder ───────────────────────────────────────────

    private function buildMainFileBody(
        string $slug,
        string $name,
        string $version,
        string $pluginType,
        array $features
    ): string {
        $constPrefix = strtoupper(str_replace('-', '_', $slug));
        $lines = [];

        $lines[] = "if (!defined('ABSPATH')) {";
        $lines[] = "    exit;";
        $lines[] = "}";
        $lines[] = "";
        $lines[] = "define('{$constPrefix}_FILE', __FILE__);";
        $lines[] = "define('{$constPrefix}_VERSION', '{$version}');";
        $lines[] = "define('{$constPrefix}_DIR', plugin_dir_path(__FILE__));";
        $lines[] = "define('{$constPrefix}_URL', plugin_dir_url(__FILE__));";
        $lines[] = "";

        if ($pluginType === 'woocommerce') {
            $lines = array_merge($lines, $this->buildWcDependencyCheck());
        } elseif ($pluginType === 'elementor') {
            $lines = array_merge($lines, $this->buildElementorDependencyCheck());
        }

        if (in_array('admin-settings', $features)) {
            $lines[] = "require_once {$constPrefix}_DIR . 'includes/class-settings.php';";
        }
        if (in_array('rest-api', $features)) {
            $lines[] = "require_once {$constPrefix}_DIR . 'includes/class-rest-api.php';";
        }
        if (in_array('admin-settings', $features) || in_array('rest-api', $features)) {
            $lines[] = "";
        }

        if (in_array('frontend-css', $features) || in_array('frontend-js', $features)) {
            $lines[] = "add_action('wp_enqueue_scripts', function () {";
            if (in_array('frontend-css', $features)) {
                $lines[] = "    wp_enqueue_style('{$slug}', {$constPrefix}_URL . 'assets/css/{$slug}.css', [], {$constPrefix}_VERSION);";
            }
            if (in_array('frontend-js', $features)) {
                $lines[] = "    wp_enqueue_script('{$slug}', {$constPrefix}_URL . 'assets/js/{$slug}.js', [], {$constPrefix}_VERSION, true);";
            }
            $lines[] = "});";
            $lines[] = "";
        }

        $lines[] = "add_action('init', function () {";
        $lines[] = "    // Plugin bootstrapped by Levi Agent.";
        $lines[] = "});";
        $lines[] = "";

        return implode("\n", $lines);
    }

    private function buildWcDependencyCheck(): array {
        return [
            "add_action('before_woocommerce_init', function () {",
            "    if (class_exists('\\Automattic\\WooCommerce\\Utilities\\FeaturesUtil')) {",
            "        \\Automattic\\WooCommerce\\Utilities\\FeaturesUtil::declare_compatibility('custom_order_tables', __FILE__);",
            "    }",
            "});",
            "",
            "add_action('plugins_loaded', function () {",
            "    if (!class_exists('WooCommerce')) {",
            "        add_action('admin_notices', function () {",
            "            echo '<div class=\"notice notice-error\"><p><strong>' . esc_html(get_file_data(__FILE__, ['Plugin Name'])[0]) . '</strong> requires WooCommerce.</p></div>';",
            "        });",
            "        return;",
            "    }",
            "});",
            "",
        ];
    }

    private function buildElementorDependencyCheck(): array {
        return [
            "add_action('plugins_loaded', function () {",
            "    if (!did_action('elementor/loaded')) {",
            "        add_action('admin_notices', function () {",
            "            echo '<div class=\"notice notice-error\"><p><strong>' . esc_html(get_file_data(__FILE__, ['Plugin Name'])[0]) . '</strong> requires Elementor.</p></div>';",
            "        });",
            "        return;",
            "    }",
            "});",
            "",
        ];
    }

    // ── Feature file builders ────────────────────────────────────────────

    private function buildFrontendJs(string $slug): string {
        $lines = [
            "'use strict';",
            "",
            "(function () {",
            "    document.addEventListener('DOMContentLoaded', function () {",
            "        // {$slug} frontend logic",
            "    });",
            "})();",
            "",
        ];
        return implode("\n", $lines);
    }

    private function buildSettingsFile(string $slug, string $name, string $pluginType): string {
        $constPrefix = strtoupper(str_replace('-', '_', $slug));
        $optionGroup = str_replace('-', '_', $slug);

        if ($pluginType === 'woocommerce') {
            return $this->buildWcSettingsFile($slug, $name, $constPrefix, $optionGroup);
        }

        $lines = [
            "<?php",
            "",
            "if (!defined('ABSPATH')) {",
            "    exit;",
            "}",
            "",
            "add_action('admin_menu', function () {",
            "    add_options_page(",
            "        '" . addslashes($name) . "',",
            "        '" . addslashes($name) . "',",
            "        'manage_options',",
            "        '{$slug}',",
            "        '{$optionGroup}_render_settings_page'",
            "    );",
            "});",
            "",
            "add_action('admin_init', function () {",
            "    register_setting('{$optionGroup}_settings', '{$optionGroup}_options');",
            "",
            "    add_settings_section(",
            "        '{$optionGroup}_main',",
            "        __('Settings', '{$slug}'),",
            "        '__return_null',",
            "        '{$slug}'",
            "    );",
            "",
            "    add_settings_field(",
            "        '{$optionGroup}_enabled',",
            "        __('Enabled', '{$slug}'),",
            "        function () {",
            "            \$options = get_option('{$optionGroup}_options', []);",
            "            \$checked = !empty(\$options['enabled']) ? 'checked' : '';",
            "            echo '<input type=\"checkbox\" name=\"{$optionGroup}_options[enabled]\" value=\"1\" ' . \$checked . ' />';",
            "        },",
            "        '{$slug}',",
            "        '{$optionGroup}_main'",
            "    );",
            "});",
            "",
            "function {$optionGroup}_render_settings_page() {",
            "    echo '<div class=\"wrap\">';",
            "    echo '<h1>' . esc_html(get_admin_page_title()) . '</h1>';",
            "    echo '<form method=\"post\" action=\"options.php\">';",
            "    settings_fields('{$optionGroup}_settings');",
            "    do_settings_sections('{$slug}');",
            "    submit_button();",
            "    echo '</form>';",
            "    echo '</div>';",
            "}",
            "",
        ];

        return implode("\n", $lines);
    }

    private function buildWcSettingsFile(string $slug, string $name, string $constPrefix, string $optionGroup): string {
        $sectionId = str_replace('-', '_', $slug);
        $lines = [
            "<?php",
            "",
            "if (!defined('ABSPATH')) {",
            "    exit;",
            "}",
            "",
            "add_filter('woocommerce_get_sections_products', function (\$sections) {",
            "    \$sections['{$sectionId}'] = __('" . addslashes($name) . "', '{$slug}');",
            "    return \$sections;",
            "});",
            "",
            "add_filter('woocommerce_get_settings_products', function (\$settings, \$current_section) {",
            "    if (\$current_section !== '{$sectionId}') {",
            "        return \$settings;",
            "    }",
            "",
            "    return [",
            "        [",
            "            'title' => __('" . addslashes($name) . " Settings', '{$slug}'),",
            "            'type'  => 'title',",
            "            'id'    => '{$sectionId}_options',",
            "        ],",
            "        [",
            "            'title'   => __('Enable', '{$slug}'),",
            "            'id'      => '{$sectionId}_enabled',",
            "            'type'    => 'checkbox',",
            "            'default' => 'yes',",
            "        ],",
            "        [",
            "            'type' => 'sectionend',",
            "            'id'   => '{$sectionId}_options',",
            "        ],",
            "    ];",
            "}, 10, 2);",
            "",
        ];

        return implode("\n", $lines);
    }

    private function buildRestApiFile(string $slug, string $name): string {
        $namespace = str_replace('-', '_', $slug);
        $lines = [
            "<?php",
            "",
            "if (!defined('ABSPATH')) {",
            "    exit;",
            "}",
            "",
            "add_action('rest_api_init', function () {",
            "    register_rest_route('{$slug}/v1', '/status', [",
            "        'methods'             => 'GET',",
            "        'callback'            => '{$namespace}_rest_status',",
            "        'permission_callback' => '__return_true',",
            "    ]);",
            "});",
            "",
            "function {$namespace}_rest_status() {",
            "    return new WP_REST_Response([",
            "        'plugin'  => '{$slug}',",
            "        'status'  => 'active',",
            "        'version' => defined('" . strtoupper($namespace) . "_VERSION') ? " . strtoupper($namespace) . "_VERSION : '0.0.0',",
            "    ], 200);",
            "}",
            "",
        ];

        return implode("\n", $lines);
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private function checkWpOrgSlugCollision(string $slug): ?array {
        if (!function_exists('plugins_api')) {
            require_once ABSPATH . 'wp-admin/includes/plugin-install.php';
        }
        $api = plugins_api('plugin_information', [
            'slug' => $slug,
            'fields' => ['sections' => false],
        ]);
        if (!is_wp_error($api) && is_object($api) && !empty($api->name)) {
            return [
                'success' => false,
                'error' => "Slug '{$slug}' already exists on wordpress.org. Choose a unique slug (e.g. your-brand-{$slug}) or set allow_wporg_slug_collision=true.",
                'conflicting_slug' => $slug,
            ];
        }
        return null;
    }

    private function cleanupDir(\WP_Filesystem_Base $filesystem, string $dir): void {
        if ($filesystem->is_dir($dir)) {
            $filesystem->delete($dir, true);
        }
    }
}
