<?php

namespace Levi\Agent\AI\Tools\Concerns;

/**
 * Shared sanitization logic for tools that write PHP files (plugins & themes).
 *
 * <code>, </code>, <pre>, </pre> in PHP string output break frontend styling
 * by wrapping content in monospace blocks. These tags are never legitimate in
 * plugin/theme frontend HTML output generated by Levi.
 */
trait SanitizesHtmlOutput {

    /**
     * Strip <code>/<pre> tags from PHP string output contexts.
     * Returns [$cleanedContent, $strippedCount].
     *
     * @return array{0: string, 1: int}
     */
    private function stripCodeTagsFromOutput(string $content, string $relativePath): array {
        $ext = strtolower(pathinfo($relativePath, PATHINFO_EXTENSION));
        if ($ext !== 'php') {
            return [$content, 0];
        }

        $hasTags = stripos($content, '<code') !== false
            || stripos($content, '</code>') !== false
            || stripos($content, '<pre') !== false
            || stripos($content, '</pre>') !== false;

        if (!$hasTags) {
            return [$content, 0];
        }

        $count = 0;

        $patterns = [
            '/<code\s[^>]*>/i',
            '/<code>/i',
            '/<\/code>/i',
            '/<pre\s[^>]*>/i',
            '/<pre>/i',
            '/<\/pre>/i',
        ];

        foreach ($patterns as $pattern) {
            $content = preg_replace($pattern, '', $content, -1, $hits);
            $count += $hits;
        }

        return [$content, $count];
    }

    /**
     * Detect remaining <code>/<pre> tags in PHP output contexts (post-strip safety net).
     * Returns a warning string or null if clean.
     */
    private function detectCodeTagsInOutput(string $content, string $relativePath): ?string {
        $ext = strtolower(pathinfo($relativePath, PATHINFO_EXTENSION));
        if ($ext !== 'php') {
            return null;
        }

        $hasTags = stripos($content, '<code') !== false
            || stripos($content, '</code>') !== false
            || stripos($content, '<pre') !== false
            || stripos($content, '</pre>') !== false;

        if (!$hasTags) {
            return null;
        }

        $found = [];

        $outputPatterns = [
            '/(?:return|echo|print)\s+[\'"].*?<\/?(?:code|pre)[\s>]/is',
            '/[\'"].*?<\/?(?:code|pre)[\s>].*?[\'"]\s*[;.]/is',
            '/<<<[\'"]?(?:HTML|EOT|HEREDOC|EOF)[\'"]?\s*\n.*?<\/?(?:code|pre)[\s>].*?\n\w+;/is',
        ];

        foreach ($outputPatterns as $pattern) {
            if (preg_match_all($pattern, $content, $matches)) {
                $found = array_merge($found, $matches[0]);
            }
        }

        if (empty($found)) {
            return null;
        }

        return 'ACHTUNG: Die Datei enthaelt noch <code>/<pre>-Tags in HTML-Output-Strings. '
            . 'Diese Tags verhindern, dass CSS-Styles greifen und zeigen Inhalte als Monospace-Text an. '
            . 'Entferne alle <code>, </code>, <pre>, </pre> Tags aus dem HTML-Output. '
            . 'HTML-Elemente wie <div>, <h3>, <span> sind Render-Output, kein "Code zum Anzeigen".';
    }
}
